#!/bin/sh

PIDFILE=/var/run/nanomq_br.pid
EXECUTABLE=/usr/bin/nanomq
CONF_FILE=/etc/nanomq.conf

case "$1" in
  start)
    echo "Starting nanomq..."
    # start (S) executable (x) in background (b) -- send in conf file and run as daemon
    start-stop-daemon -S -x "$EXECUTABLE" -b -m -p "$PIDFILE" -- start --conf "$CONF_FILE"
    ;;
  stop)
    echo "Stopping nanomq..."
    # stop (K) and remove pidfile
    start-stop-daemon -K -p "$PIDFILE"
    rm "$PIDFILE"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: {start|stop|restart/reload}"
    exit 1
esac
