#!/bin/sh


do_start() {
    # lo
    ip addr add 127.0.0.1/8 dev lo
    ip link set dev lo up

    # eth0
    ip link set dev eth0 up

    # eth1
    ip link set dev eth1 up
    ethtool --set-plca-cfg eth1 enable on node-id 2 node-cnt 8 to-tmr 0x20

    # can0
    ip link set dev can0 type can bitrate 500000 listen-only off restart-ms 50
    ip link set dev can0 txqueuelen 100
    ip link set dev can0 up

    # wlan1 is 2.4 GHz
    ip link set dev wlan1 up
    start-stop-daemon -S -x /usr/sbin/wpa_supplicant -b -m \
        -p /var/run/wpa_supplicant.wlan1.pid \
        -- -i wlan1 -c /etc/wpa_supplicant_base.conf -f /var/log/wpa1.log

    # wlan0 is 900 MHz
    ip link set dev wlan0 up
    start-stop-daemon -S -x /usr/sbin/wpa_supplicant -b -m \
        -p /var/run/wpa_supplicant.wlan0.pid \
        -- -i wlan0 -c /etc/wpa_supplicant_halow.conf -f /var/log/wpa0.log

   # LTE
   ip link set dev wwp1s0u1u1i5 down
   echo 'Y' | tee /sys/class/net/wwp1s0u1u1i5/qmi/raw_ip
   ip link set dev wwp1s0u1u1i5 up
   qmicli -p -d /dev/cdc-wdm0 --device-open-net='net-raw-ip|net-no-qos-header' --wds-start-network="apn='NXTGENPHONE',ip-type=4" --client-no-release-cid


    # Loose RPF for asymmetric multi-path
    sysctl -w net.ipv4.conf.all.rp_filter=2
    sysctl -w net.ipv4.conf.wlan0.rp_filter=2
    sysctl -w net.ipv4.conf.wlan1.rp_filter=2


    # Add to do_start() after dhcpcd has applied IPs:

    # Reply-on-same-interface for HaLow
    ip route replace default via 10.42.0.1 dev wlan0 table 100
    ip rule add fwmark 0x1 table 100 2>/dev/null

    # Mark connections coming in on wlan0; restore mark on outgoing packets
    iptables -t mangle -A PREROUTING -i wlan0 -j CONNMARK --set-mark 0x1
    iptables -t mangle -A OUTPUT -j CONNMARK --restore-mark

}

do_stop() {
    start-stop-daemon -K -p /var/run/wpa_supplicant.wlan1.pid
    rm -f /var/run/wpa_supplicant.wlan1.pid
    start-stop-daemon -K -p /var/run/wpa_supplicant.wlan0.pid
    rm -f /var/run/wpa_supplicant.wlan0.pid

    iptables -t mangle -D OUTPUT -j CONNMARK --restore-mark 2>/dev/null
    iptables -t mangle -D PREROUTING -i wlan0 -j CONNMARK --set-mark 0x1 2>/dev/null
    ip rule del fwmark 0x1 table 100 2>/dev/null
    ip route flush table 100 2>/dev/null

    ip link set dev wlan0 down
    ip link set dev wlan1 down
    ip link set dev eth1 down
    ip link set dev eth0 down
    ip link set dev lo down
}

if [ "$1" = init ]; then
    do_start
elif [ "$1" = deinit ]; then
    do_stop
else
    echo "Usage: {init|deinit}"
fi
