version: "3.8"
services:
    odysseus:
        build: .
        command: /bin/bash
        privileged: true
        tty: true
        # for fakeroot failure
        ulimits:
          nofile:
            soft: 1024
            hard: 1048576
        volumes:
            - ./odysseus_tree:/home/odysseus/build/odysseus_tree
            - shared_data:/home/odysseus/shared_data
            - ./outputs:/home/odysseus/outputs
        environment:
            - BR2_DL_DIR=/home/odysseus/shared_data/dl 
            - BR2_CCACHE_DIR=/home/odysseus/shared_data/ccache

volumes:
    shared_data:
        labels:
            com.northeastern_electric_racing.description: "Shared output between buildroot runs"

            
