ctrl_interface=/var/run/wpa_supplicant_s1g

sae_pwe=1
max_peer_links=10
mesh_fwding=1

network={
    country="US"
    ssid=NER_HalowMesh
    key_mgmt=SAE
    mode=5
    s1g_prim_chwidth=0
    s1g_prim_1mhz_chan_index=0
    channel=28
    op_class=71
    country=“US”
    mesh_rssi_threshold=-85
    sae_password="password"
    pairwise=CCMP
    ieee80211w=2
    beacon_int=1000
    dtim_period=1
}


