# NER: new package
NERQT6CHARTS_VERSION = $(NERQT6_VERSION)
NERQT6CHARTS_SITE = $(NERQT6_SITE)
NERQT6CHARTS_SOURCE = qtcharts-$(NERQT6_SOURCE_TARBALL_PREFIX)-$(NERQT6CHARTS_VERSION).tar.xz
NERQT6CHARTS_INSTALL_STAGING = YES
NERQT6CHARTS_SUPPORTS_IN_SOURCE_BUILD = NO

NERQT6CHARTS_CMAKE_BACKEND = ninja

NERQT6CHARTS_LICENSE = GPL-3.0 with exception

NERQT6CHARTS_CONF_OPTS = \
	-DQT_HOST_PATH=$(HOST_DIR) \
	-DBUILD_WITH_PCH=OFF \
	-DQT_BUILD_EXAMPLES=OFF \
	-DQT_BUILD_TESTS=OFF

NERQT6CHARTS_DEPENDENCIES = \
	host-pkgconf \
	nerqt6base

# add declarative as a dep for this if it is being used
ifeq ($(BR2_PACKAGE_NERQT6DECLARATIVE),y)
NERQT6CHARTS_DEPENDENCIES += nerqt6declarative
endif

$(eval $(cmake-package))
