#!/bin/sh


# Assure that the kernel has module support.
[ -e /proc/ksyms ] || [ -e /proc/modules ] || exit 0

case "$1" in
    start)

        # Exit if there's no modules file or there are no
        # valid entries
        [ -r /etc//modules ] &&
            grep -Eqv '^($|#)' /etc/modules ||
            exit 0

        echo "Loading modules"

        # Only try to load modules if the user has actually given us
        # some modules to load.
        while read -r module; do

            # Ignore comments and blank lines.
            case "$module" in
                ""|"#"*) continue ;;
            esac

            # Attempt to load the module            
            # Note: args should be specified in /etc/modprobe.d
            # Print the module name if successful,
            # otherwise take note.
            if modprobe "${module}" >/dev/null; then
                echo "${module} SUCCESS"
            else
                echo "${module} FAILED"
            fi
        done < /etc/modules
        ;;
    *)
        echo "Usage: ${0} {start}"
        exit 1
        ;;
esac
