#!/bin/sh

PIDFILE=/var/run/calypso.pid
EXECUTABLE=/usr/bin/calypso

case "$1" in
  start)
    echo "Starting calypso..."
    # start (S) executable (x) in background (b), make pid file (m) at p
    start-stop-daemon -S -x "$EXECUTABLE" -b -m -p "$PIDFILE" -- mqtt localhost:1883
    ;;
  stop)
    echo "Stopping calypso..."
    # stop (K) and remove pidfile
    start-stop-daemon -K -p "$PIDFILE"
    rm "$PIDFILE"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: {start|stop|restart/reload}"
    exit 1
esac
