#!/usr/bin/env python3

import os
from vars import HALOW_INTERFACE


def main():

    print("Undoing mapped IP")
    os.system("sudo dhclient -r")

    print("Removing connection to AP")
    os.system("sudo iwconfig {} essid off".format(HALOW_INTERFACE))
    os.system("sudo ifdown {} --force".format(HALOW_INTERFACE))
    os.system("sudo ifconfig {} up".format(HALOW_INTERFACE))

    print("Complete!")


if __name__ == "__main__":
    main()
