MM6108_DRIVER_VERSION = 1.17.9
MM6108_DRIVER_SITE = https://github.com/MorseMicro/morse_driver
MM6108_DRIVER_SITE_METHOD = git
MM6108_DRIVER_GIT_SUBMODULES = YES
MM6108_DRIVER_LICENSE = GPLv2
# set the makefile KDIR to buildroot kernel, as otherwise it will use host headers
MM6108_DRIVER_MODULE_MAKE_OPTS = KERNEL_SRC=$(LINUX_DIR) CONFIG_WLAN_VENDOR_MORSE=m "KCFLAGS=-pipe -Wno-error=unused-variable -Wno-error=enum-int-mismatch"


MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_SDIO=$(BR2_PACKAGE_MM6108_DRIVER_SDIO)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_USB=$(BR2_PACKAGE_MM6108_DRIVER_USB)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_SDIO_ALIGNMENT=$(BR2_PACKAGE_MM6108_DRIVER_SDIO_ALIGNMENT)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_SPI=$(BR2_PACKAGE_MM6108_DRIVER_SPI)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_SPI_RK3288=$(BR2_PACKAGE_MM6108_DRIVER_SPI_RK3288)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_USER_ACCESS=$(BR2_PACKAGE_MM6108_DRIVER_USER_ACCESS)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_VENDOR_COMMAND=$(BR2_PACKAGE_MM6108_DRIVER_VENDOR_COMMAND)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_COUNTRY=$(BR2_PACKAGE_MM6108_DRIVER_COUNTRY)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_DEBUG_MASK=$(BR2_PACKAGE_MM6108_DRIVER_DEBUG_MASK)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_SDIO_RESET_TIME=$(BR2_PACKAGE_MM6108_DRIVER_SDIO_RESET_TIME)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_POWERSAVE_MODE=$(BR2_PACKAGE_MM6108_DRIVER_POWERSAVE_MODE)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_DHCP_OFFLOAD=$(BR2_PACKAGE_MM6108_DRIVER_DHCP_OFFLOAD)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_ARP_OFFLOAD=$(BR2_PACKAGE_MM6108_DRIVER_ARP_OFFLOAD)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_WATCHDOG_RESET_DEFAULT_DISABLED=$(BR2_PACKAGE_MM6108_DRIVER_WATCHDOG_RESET_DEFAULT_DISABLED)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_DISABLE_CHANNEL_SURVEY=$(BR2_PACKAGE_MM6108_DRIVER_DISABLE_CHANNEL_SURVEY)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_ANDROID=$(BR2_PACKAGE_MM6108_DRIVER_ANDROID)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_MONITOR=$(BR2_PACKAGE_MM6108_DRIVER_MONITOR)

MM6108_DRIVER_MODULE_MAKE_OPTS += CONFIG_MORSE_DEBUGFS=$(BR2_PACKAGE_MM6108_DRIVER_DEBUGFS)



$(eval $(kernel-module))
$(eval $(generic-package))
