#!/bin/bash

# the parameters to pass into start.py
START_PARAMETERS="0 0 US"


if [ "$EUID" -eq 0 ]; then
  echo "You are not allowed to run this command as root."
  exit 1
fi

if [ "$1" == "start" ];
then
    echo "Begin start.py ----------------"
    python -u $HOME/nrc_pkg/script/start.py $START_PARAMETERS
    echo "End start.py ----------------"

elif [ "$1" == "stop" ];
then
    echo "Begin stop.py -----------------"
    python -u $HOME/nrc_pkg/script/stop.py
    echo "End stop.py -----------------"

elif [ "$1" == "startup-logs" ];
then 
  # this displays the most recent invocation ID of nrc-autostart and filters the logs by that invocation, otherwise journalctl would display all logs since nrc-autostart was first started
  journalctl -u nrc-autostart.service  -e _SYSTEMD_INVOCATION_ID="$(systemctl show -p InvocationID --value nrc-autostart.service)"
else
  echo "Run with start|stop|startup-logs to configure start.py/stop.py accordingly, or get logs"
fi
