WHEEL_BUTTONS_VERSION = 0.1
WHEEL_BUTTONS_SITE = $(BR2_EXTERNAL_ODY_TREE_PATH)/sources/wheel_buttons
WHEEL_BUTTONS_SITE_METHOD = local
WHEEL_BUTTONS_CMAKE_BACKEND = ninja

WHEEL_BUTTONS_DEPENDENCIES += libgpiod2

define WHEEL_BUTTONS_INSTALL_INIT_SYSV
    $(INSTALL) -D -m 0755 $(WHEEL_BUTTONS_PKGDIR)/S97wheel-buttons $(TARGET_DIR)/etc/init.d/S97wheel-buttons
endef

$(eval $(cmake-package))
