# NER: new package!
NERQT6DECLARATIVE_VERSION = $(NERQT6_VERSION)
NERQT6DECLARATIVE_SITE = $(NERQT6_SITE)
NERQT6DECLARATIVE_SOURCE = qtdeclarative-$(NERQT6_SOURCE_TARBALL_PREFIX)-$(NERQT6DECLARATIVE_VERSION).tar.xz
NERQT6DECLARATIVE_INSTALL_STAGING = YES

NERQT6DECLARATIVE_CMAKE_BACKEND = ninja

NERQT6DECLARATIVE_LICENSE = \
	GPL-2.0+ or LGPL-3.0, \
	GPL-3.0 with exception (tools), \
	GFDL-1.3 (docs), \
	BSD-3-Clause

NERQT6DECLARATIVE_LICENSE_FILES = \
	LICENSES/BSD-3-Clause.txt \
	LICENSES/GFDL-1.3-no-invariants-only.txt \
	LICENSES/GPL-2.0-only.txt \
	LICENSES/GPL-3.0-only.txt \
	LICENSES/LGPL-3.0-only.txt \
	LICENSES/Qt-GPL-exception-1.0.txt

NERQT6DECLARATIVE_CONF_OPTS = \
	-DQT_HOST_PATH=$(HOST_DIR) \
	-DBUILD_WITH_PCH=OFF \
	-DQT_BUILD_EXAMPLES=OFF \
	-DQT_BUILD_TESTS=OFF

NERQT6DECLARATIVE_DEPENDENCIES = \
	host-pkgconf \
	nerqt6base \
	nerqt6shadertools \
	host-nerqt6declarative

HOST_NERQT6DECLARATIVE_DEPENDENCIES = host-nerqt6shadertools

$(eval $(cmake-package))
$(eval $(host-cmake-package))
