#!/bin/sh

start() {
        printf "Setting ublox settings"
        # turn on PPS w/o fix
        ubxtool -P 18 -v 2 -p CFG-TP5,0,2,0,1000000,1000000,100000,100000,0,0x77 --device /dev/ttyAMA5 >> /dev/null &
}

case "$1" in
  start)
        start
        ;;
  *)
        echo "Usage: $0 {start}"
        exit 1
        ;;
esac
