#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
        printf "Starting quicknet: "
        /sbin/quicknet init
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  stop)
        printf "Stopping quicknet: "
        /sbin/quicknet deinit
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
