#!/bin/sh

case "$1" in
  start)
    echo "Starting LEDs..."
    /usr/bin/alfa-led-sta
    ;;
  stop)
    echo -n "Stopping LEDs..."
    /usr/bin/alfa-led-sta
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

