#!/usr/bin/env python3

import os
from vars import AP_NAME


def main():

    print("Undoing mapped IP")
    os.system("sudo dhclient -r")

    print("Removing connection to AP")
    os.system("sudo iwconfig {} essid off".format(AP_NAME))
    os.system("sudo ifdown {} --force".format(AP_NAME))
    os.system("sudo ifconfig {} up".format(AP_NAME))

    print("Complete!")


if __name__ == "__main__":
    main()
