# NER: new package
NERQT6MQTT_VERSION = $(NERQT6_VERSION)
NERQT6MQTT_SITE = https://github.com/qt/qtmqtt.git
NERQT6MQTT_SITE_METHOD = git
NERQT6MQTT_INSTALL_STAGING = YES
NERQT6MQTT_SUPPORTS_IN_SOURCE_BUILD = NO

NERQT6MQTT_CMAKE_BACKEND = ninja

NERQT6MQTT_LICENSE = GPL-3.0 with exception

NERQT6MQTT_CONF_OPTS = \
	-DQT_HOST_PATH=$(HOST_DIR) \
	-DBUILD_WITH_PCH=OFF \
	-DQT_BUILD_EXAMPLES=OFF \
	-DQT_BUILD_TESTS=OFF

NERQT6MQTT_DEPENDENCIES = \
	host-pkgconf \
	nerqt6base

$(eval $(cmake-package))
