#!/bin/sh

do_start() {
   # lo
   ip addr add 127.0.0.1/8 dev lo
   ip link set dev lo up
   
   # eth0
   ip link set dev eth0 up

   # can0
   ip link set dev can0 type can bitrate 1000000 listen-only off
   ip link set dev can0 up

   # bond0
   modprobe bonding

   # add_master
   ip link add dev bond0 type bond 

   # setup_master
   ip link set dev bond0 type bond mode active-backup miimon 100
   
   # enslave_slaves
   ip link set dev wlan0 master bond0
   ip link set dev wlan1 master bond0

   ip link set dev bond0 type bond primary wlan1 
 
   # add wlan0
   ip link set dev wlan0 up

   # add wlan1
   ip link set dev wlan1 up

   start-stop-daemon -S -x /usr/sbin/wpa_supplicant -b -m -p /var/run/wpa_supplicant.wlan1.pid -- -i wlan1 -c /etc/wpa_supplicant_base.conf -f /var/log/wpa1.log -d

   start-stop-daemon -S -x /usr/sbin/wpa_supplicant -b -m -p /var/run/wpa_supplicant.wlan0.pid -- -i wlan0 -c /etc/wpa_supplicant_halow.conf -f /var/log/wpa0.log -d

}

do_stop() {
   
   start-stop-daemon -K -p /var/run/wpa_supplicant.wlan1.pid
   rm /var/run/wpa_supplicant.wlan1.pid
   start-stop-daemon -K -p /var/run/wpa_supplicant.wlan0.pid
   rm /var/run/wpa_supplicant.wlan0.pid

      
   ip link set dev wlan0 down
   ip link set dev wlan1 down
   ip link set dev bond0 down
   ip link set dev eth0 down
   ip link set dev lo down
}


if [ "$1" = init ];
then
   do_start
elif [ "$1" = deinit ];
then
   do_stop
else
   echo "Usage: {init|deinit}"
fi
