noipv6
noipv6rs

# Global options
hostname
persistent
option rapid_commit
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
option ntp_servers
require dhcp_server_identifier
slaac private

# Don't touch these interfaces
denyinterfaces lo

# eth0 main LAN
interface eth0
    static ip_address=192.168.100.11/24
    static routers=192.168.100.1
    static domain_name_servers=192.168.100.1

# wlan0 900 MHz
interface wlan0
    static ip_address=10.42.0.1/24
    # No default route from this interface
    nohook resolv.conf
