#!/bin/sh

PIDFILE=/var/run/socketcand_br.pid
EXECUTABLE=/usr/bin/socketcand
CAN_INTERFACE=/etc/nanomq.conf

case "$1" in
  start)
    echo "Starting socketcan..."
    # start (S) executable (x) in background (b) -- send in conf file and run as daemon
    start-stop-daemon -S -x "$EXECUTABLE" -b -m -p "$PIDFILE" -- -l $CAN_INTERFACE -i eth0
    ;;
  stop)
    echo "Stopping socketcan..."
    # stop (K) and remove pidfile
    start-stop-daemon -K -p "$PIDFILE"
    rm "$PIDFILE"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: {start|stop|restart/reload}"
    exit 1
esac
