# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_data.proto
# Protobuf Python Version: 4.25.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11server_data.proto\x12\rserverdata.v2\"H\n\nServerData\x12\x0c\n\x04unit\x18\x02 \x01(\t\x12\x0f\n\x07time_us\x18\x03 \x01(\x04\x12\x0e\n\x06values\x18\x04 \x03(\x02J\x04\x08\x01\x10\x02R\x05valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVERDATA']._serialized_start=36
  _globals['_SERVERDATA']._serialized_end=108
# @@protoc_insertion_point(module_scope)
