#!/bin/sh
#
# NER: copied from br source and edited
# Starts the gps daemon.
#

NAME=gpsd
DAEMON=/usr/sbin/$NAME
DEVICES="/dev/pps0 /dev/ttyAMA5"
PIDFILE=/var/run/$NAME.pid

start() {
        printf "Starting $NAME: "
        # add -n option to run w/o waiting and -r option to allow time w/o fix
        start-stop-daemon -S -q -p $PIDFILE --exec $DAEMON -- -P $PIDFILE $DEVICES -n -r && echo "OK" || echo "Failed"
}
stop() {
        printf "Stopping $NAME: "
        start-stop-daemon -K -q -p $PIDFILE && echo "OK" || echo "Failed"
        rm -f $PIDFILE
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
