#!/bin/sh

PIDFILE=/var/run/odysseus-daemon.pid
EXECUTABLE=/usr/bin/odysseus-daemon


case "$1" in
  start)
    echo "Starting odysseus_daemon..."
    # start (S) executable (x) in background (b), make pid file (m) at p
    start-stop-daemon -S -x "$EXECUTABLE" -b -m -p "$PIDFILE" --  --logger --lockdown --usbs-locked "1-1.1" "1-1.3" --sys --scylla-url 192.168.100.11:8000 -f /root/data
    ;;
  stop)
    echo "Stopping odysseus_daemon..."
    # stop (K) and remove pidfile
    start-stop-daemon -K -p "$PIDFILE"
    rm "$PIDFILE"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: {start|stop|restart/reload}"
    exit 1
esac
