noipv6
noipv6rs

hostname
persistent
option rapid_commit
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
option ntp_servers
require dhcp_server_identifier
slaac private

denyinterfaces lo eth0 eth1 can0 docker0

# wlan1 is the 2.4 GHz
interface wlan1
    static ip_address=192.168.100.12/24
    static routers=192.168.100.1
    static domain_name_servers=192.168.100.1

# wlan0 is the 900 MHz
interface wlan0
    static ip_address=10.42.0.2/24
    # No default route here
    nohook resolv.conf, mtu, ntp
