ctrl_interface=/var/run/wpa_supplicant_halow

country=US
network={
    ssid="NER_Halow"
    key_mgmt=NONE
    scan_freq= 2412
    freq_list= 2412
    bgscan=""
}
ignore_old_scan_res=1
ap_scan=1
autoscan=

